name: grun_adminapp
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  another_flushbar: ^1.12.30
  auto_size_text: ^3.0.0
  bitsdojo_window: ^0.1.5
  cached_network_image: ^3.2.3
  cloudinary_sdk: ^5.0.0+1
  file_selector: ^0.9.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.4.0
  http: ^0.13.5
  provider: ^6.0.5
  simple_animations: ^5.0.0+3
  syncfusion_flutter_datagrid: ^21.2.4
  syncfusion_flutter_datepicker: ^21.2.5
  syncfusion_flutter_charts: ^21.2.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/light_logo.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/dark_logo.png"
  windows:
    generate: true
    icon_size: 256

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Paralucent
      fonts:
        - asset: fonts/paralucent.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat.ttf
        - asset: fonts/montserrat-regular.ttf
