name: grun_adminapp
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  http: ^0.13.5
  font_awesome_flutter: ^10.4.0
  marquee: ^2.2.3
  provider: ^6.0.5
  simple_animations: ^5.0.0+3
  auto_size_text: ^3.0.0
  scrollable_positioned_list: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Paralucent
      fonts:
        - asset: fonts/paralucent.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat.ttf
        - asset: fonts/montserrat-regular.ttf
